# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/42236fb4-ab0d-450d-98ab-a91a89e447ad";
      fsType = "btrfs";
    options = [
      "subvol=@"
      "discard"
      "noatime"
    ];
    };

  boot.initrd.luks.devices."cryptnix" = {
    device = "/dev/disk/by-uuid/b58fcfa2-9dee-4b66-9dd0-3c2e977a8f1a";
    allowDiscards = true;
  };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/42236fb4-ab0d-450d-98ab-a91a89e447ad";
      fsType = "btrfs";
    options = [
      "subvol=@nix"
      "discard"
      "noatime"
      "nodev"
    ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/42236fb4-ab0d-450d-98ab-a91a89e447ad";
      fsType = "btrfs";
    options = [
      "subvol=@swap"
      "discard"
      "noatime"
      "nosuid"
      "nodev"
      "noexec"
    ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/42236fb4-ab0d-450d-98ab-a91a89e447ad";
      fsType = "btrfs";
    options = [
      "subvol=@home"
      "discard"
      "noatime"
      "nodev"
      "nosuid"
    ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/347C-3AB8";
      fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
      "noatime"
      "nosuid"
      "nodev"
      "noexec"
      "errors=remount-ro"
    ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
