# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  hardware.amdgpu.initrd.enable = true;

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "noatime"
      "compress=zstd:3"
      "discard=async"
    ];
  };

  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/c646880d-7fbe-472f-ad36-dae67e32dd3a";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "noatime"
      "compress=zstd:3"
      "discard=async"
      "nosuid"
      "nodev"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "noatime"
      "compress=zstd:3"
      "discard=async"
      "nodev"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/347C-3AB8";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
      "noatime"
      "nodev"
      "nosuid"
      "noexec"
    ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@snapshots"
      "noatime"
      "discard=async"
      "nosuid"
      "nodev"
    ];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@data"
      "defaults"
      "noatime"
      "discard=async"
      "nosuid"
      "nodev"
      "noexec"
      "compress=zstd:9"
      "x-gvfs-show"
    ];
  };

  fileSystems."/mnt/hdd" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@hdd"
      "defaults"
      "noatime"
      "discard=async"
      "nosuid"
      "nodev"
      "noexec"
      "compress=zstd:9"
      "x-gvfs-show"
    ];
  };

  fileSystems."/mnt/masterdata" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@masterdata"
      "defaults"
      "noatime"
      "discard=async"
      "nosuid"
      "nodev"
      "noexec"
      "compress=zstd:9"
      "x-gvfs-show"
    ];
  };

  fileSystems."/mnt/netac" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@netac"
      "defaults"
      "noatime"
      "discard=async"
      "nosuid"
      "nodev"
      "noexec"
      "compress=zstd:9"
      "x-gvfs-show"
    ];
  };

  # Declaratively enforce directory ownership and permissions at boot.
  # This maintains strict privilege separation without requiring imperative execution.
  systemd.tmpfiles.rules = [
    "d /mnt/data 0755 izvyk users - -"
    "d /mnt/hdd 0755 izvyk users - -"
    "d /mnt/netac 0755 izvyk users - -"
    "d /mnt/masterdata 0755 izvyk users - -"
  ];

  fileSystems."/swap" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@swap"
      "noatime"
      "discard=async"
      "nosuid"
      "noexec"
    ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 16 * 1024;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
